version: 2.1

executors:
  nodejs:
      docker:
        - image: circleci/node

commands:
  ceckout-and-restore:
    description: "restore cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - attach_workspace:
          at: ~/
  save-node-modules-cache:
    steps:
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  build:
    executor: nodejs
    steps:
      - ceckout-and-restore
      - run: npm install --no-save
      - save-node-modules-cache
      - run: npm run build && touch test_persist.md
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  test:
    executor: nodejs
    steps:
      - ceckout-and-restore
      - run: npm run test

  publish:
    executor: nodejs
    steps:
      - ceckout-and-restore
      - run:
          command: |
            ls
            echo: this will be a npm publish place

workflows:
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test