version: 2.1

executors:
  nodejs:
      docker:
        - image: circleci/node:7.10

commands:
  ceckout-and-restore-cache:
    description: "restore cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
  save-node-modules-cache:
    steps:
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  build:
    executor: nodejs
    steps:
      - ceckout-and-restore-cache
      - run: npm install
      - save-node-modules-cache
      - run: npm run build

  test:
    executor: nodejs
    steps:
      - ceckout-and-restore-cache
      - run: npm install
      - run: npm run build
      - run: npm run test

workflows:
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build